# Generated by Django 5.2.16 on 2026-07-20 00:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('valor_semanal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor semanal (R$)')),
                ('dia_vencimento', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Padrão: dia da semana do início da locação', verbose_name='dia de vencimento semanal')),
                ('caucao_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='caução acordada (R$)')),
                ('km_entrega', models.PositiveIntegerField(verbose_name='KM na entrega')),
                ('km_devolucao', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na devolução')),
                ('limite_km', models.CharField(choices=[('ilimitado', 'Ilimitado'), ('limitado', 'Limitado')], default='ilimitado', max_length=10, verbose_name='limite de km')),
                ('franquia_km_mensal', models.PositiveIntegerField(blank=True, help_text='Somente quando limitado', null=True, verbose_name='franquia mensal (km)')),
                ('taxa_km_excedido', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='taxa por km excedido (R$)')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='pessoas.cliente', verbose_name='cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'alocação',
                'verbose_name_plural': 'alocações',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAlocacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('valor_semanal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor semanal (R$)')),
                ('dia_vencimento', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Padrão: dia da semana do início da locação', verbose_name='dia de vencimento semanal')),
                ('caucao_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='caução acordada (R$)')),
                ('km_entrega', models.PositiveIntegerField(verbose_name='KM na entrega')),
                ('km_devolucao', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na devolução')),
                ('limite_km', models.CharField(choices=[('ilimitado', 'Ilimitado'), ('limitado', 'Limitado')], default='ilimitado', max_length=10, verbose_name='limite de km')),
                ('franquia_km_mensal', models.PositiveIntegerField(blank=True, help_text='Somente quando limitado', null=True, verbose_name='franquia mensal (km)')),
                ('taxa_km_excedido', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='taxa por km excedido (R$)')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'historical alocação',
                'verbose_name_plural': 'historical alocações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrocaTemporaria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_retirada', models.DateField(verbose_name='data de retirada')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='data de devolução')),
                ('km_retirada', models.PositiveIntegerField(verbose_name='KM na retirada')),
                ('km_devolucao', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na devolução')),
                ('motivo', models.CharField(blank=True, help_text='Ex.: manutenção do carro principal', max_length=200, verbose_name='motivo')),
                ('valor_semanal_ajustado', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = mantém o valor da alocação; muda quando a categoria é diferente', max_digits=8, null=True, verbose_name='valor semanal durante a troca (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alocacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alocacoes.alocacao', verbose_name='alocação')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veiculo_substituto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.veiculo', verbose_name='veículo substituto')),
            ],
            options={
                'verbose_name': 'historical troca temporária',
                'verbose_name_plural': 'historical trocas temporárias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TrocaTemporaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(verbose_name='data de retirada')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='data de devolução')),
                ('km_retirada', models.PositiveIntegerField(verbose_name='KM na retirada')),
                ('km_devolucao', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na devolução')),
                ('motivo', models.CharField(blank=True, help_text='Ex.: manutenção do carro principal', max_length=200, verbose_name='motivo')),
                ('valor_semanal_ajustado', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = mantém o valor da alocação; muda quando a categoria é diferente', max_digits=8, null=True, verbose_name='valor semanal durante a troca (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trocas', to='alocacoes.alocacao', verbose_name='alocação')),
                ('veiculo_substituto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trocas_como_substituto', to='frota.veiculo', verbose_name='veículo substituto')),
            ],
            options={
                'verbose_name': 'troca temporária',
                'verbose_name_plural': 'trocas temporárias',
                'ordering': ['-data_retirada'],
            },
        ),
        migrations.AddConstraint(
            model_name='alocacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('veiculo',), name='uma_alocacao_ativa_por_veiculo'),
        ),
    ]
