# Generated by Django 5.2.16 on 2026-08-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alocacoes', '0001_initial'),
        ('frota', '0004_seed_categorias'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trocatemporaria',
            constraint=models.UniqueConstraint(condition=models.Q(('data_devolucao__isnull', True)), fields=('alocacao',), name='uma_troca_aberta_por_alocacao'),
        ),
        migrations.AddConstraint(
            model_name='trocatemporaria',
            constraint=models.UniqueConstraint(condition=models.Q(('data_devolucao__isnull', True)), fields=('veiculo_substituto',), name='uma_troca_aberta_por_substituto'),
        ),
    ]
