# Generated by Django 5.2.16 on 2026-08-18 17:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alocacoes', '0002_trocatemporaria_uma_troca_aberta_por_alocacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVistoria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (entrega ao cliente)'), ('saida', 'Saída (devolução do cliente)')], max_length=10, verbose_name='tipo')),
                ('data', models.DateField(verbose_name='data')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM no painel')),
                ('combustivel', models.CharField(blank=True, choices=[('cheio', 'Cheio'), ('tres_quartos', '3/4'), ('meio', '1/2'), ('um_quarto', '1/4'), ('reserva', 'Reserva')], max_length=15, verbose_name='combustível')),
                ('avarias', models.TextField(blank=True, help_text='Riscos, amassados, trincas — onde e como estão', verbose_name='marcas e avarias')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='foto/PDF do checklist preenchido')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alocacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alocacoes.alocacao', verbose_name='alocação')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vistoria',
                'verbose_name_plural': 'historical vistorias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (entrega ao cliente)'), ('saida', 'Saída (devolução do cliente)')], max_length=10, verbose_name='tipo')),
                ('data', models.DateField(verbose_name='data')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM no painel')),
                ('combustivel', models.CharField(blank=True, choices=[('cheio', 'Cheio'), ('tres_quartos', '3/4'), ('meio', '1/2'), ('um_quarto', '1/4'), ('reserva', 'Reserva')], max_length=15, verbose_name='combustível')),
                ('avarias', models.TextField(blank=True, help_text='Riscos, amassados, trincas — onde e como estão', verbose_name='marcas e avarias')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('foto', models.FileField(blank=True, null=True, upload_to='vistorias/', verbose_name='foto/PDF do checklist preenchido')),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vistorias', to='alocacoes.alocacao', verbose_name='alocação')),
            ],
            options={
                'verbose_name': 'vistoria',
                'ordering': ['-data', '-pk'],
            },
        ),
    ]
