# Generated by Django 5.2.16 on 2026-07-21 16:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0002_fornecedor_historicalfornecedor'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaoAutuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('esfera', models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('estadual', 'Estadual'), ('federal', 'Federal')], max_length=10, verbose_name='esfera')),
                ('portal', models.CharField(blank=True, max_length=200, verbose_name='portal/site')),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='login/usuário')),
                ('senha', models.CharField(blank=True, help_text='Sensível — mascarada na interface', max_length=200, verbose_name='senha')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de atendimento')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('procedimento', models.TextField(blank=True, help_text='Ex.: solicitar FICI; docs: doc. do veículo, CNH do motorista, termo de entrega', verbose_name='procedimento e documentos exigidos')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço físico')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'órgão autuador',
                'verbose_name_plural': 'órgãos autuadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrgaoAutuador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=80, verbose_name='nome')),
                ('esfera', models.CharField(blank=True, choices=[('municipal', 'Municipal'), ('estadual', 'Estadual'), ('federal', 'Federal')], max_length=10, verbose_name='esfera')),
                ('portal', models.CharField(blank=True, max_length=200, verbose_name='portal/site')),
                ('login', models.CharField(blank=True, max_length=100, verbose_name='login/usuário')),
                ('senha', models.CharField(blank=True, help_text='Sensível — mascarada na interface', max_length=200, verbose_name='senha')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de atendimento')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('procedimento', models.TextField(blank=True, help_text='Ex.: solicitar FICI; docs: doc. do veículo, CNH do motorista, termo de entrega', verbose_name='procedimento e documentos exigidos')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço físico')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical órgão autuador',
                'verbose_name_plural': 'historical órgãos autuadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da infração')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='código da infração')),
                ('ait', models.CharField(blank=True, max_length=30, verbose_name='AIT')),
                ('num_processamento', models.CharField(blank=True, max_length=30, verbose_name='nº de processamento')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição da infração')),
                ('local', models.CharField(blank=True, max_length=120, verbose_name='local')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor (R$)')),
                ('pontos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pontos na CNH')),
                ('resultado', models.CharField(choices=[('em_aberto', 'Em aberto'), ('advertencia', 'Convertida em advertência'), ('penalidade', 'Penalidade confirmada'), ('suspensa', 'Suspensa'), ('divida_ativa', 'Dívida ativa'), ('nao_exigivel', 'Não exigível'), ('cancelada', 'Cancelada')], default='em_aberto', max_length=15, verbose_name='resultado/situação')),
                ('tipo_condutor', models.CharField(choices=[('cliente', 'O próprio cliente'), ('outra_pessoa', 'Condutor autorizado / outra pessoa'), ('empresa', 'Empresa (dono absorve)')], default='cliente', max_length=15, verbose_name='tipo de condutor')),
                ('fici_status', models.CharField(choices=[('pendente', 'Pendente'), ('indicado', 'Indicado'), ('prazo_perdido', 'Prazo perdido')], default='pendente', max_length=15, verbose_name='indicação (FICI)')),
                ('fici_prazo', models.DateField(blank=True, null=True, verbose_name='prazo limite de indicação')),
                ('pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='pagamento')),
                ('pago_por', models.CharField(blank=True, max_length=80, verbose_name='pago por')),
                ('repasse', models.CharField(choices=[('nao_se_aplica', 'Não se aplica'), ('a_cobrar', 'A cobrar'), ('incluida_nd', 'Incluída em ND'), ('recebido', 'Recebido')], default='a_cobrar', max_length=15, verbose_name='repasse ao cliente')),
                ('responsavel', models.CharField(choices=[('cliente', 'Cliente da alocação'), ('condutor', 'Condutor identificado'), ('empresa', 'Empresa (absorve)'), ('vendedor', 'Vendedor anterior')], default='cliente', max_length=10, verbose_name='responsável pelo valor')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente_alocacao', models.ForeignKey(blank=True, help_text='Quem estava com o carro na data (preenchido automaticamente)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='pessoas.cliente', verbose_name='cliente da alocação')),
                ('condutor_autorizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='pessoas.condutorautorizado', verbose_name='condutor identificado')),
                ('multa_origem', models.ForeignKey(blank=True, help_text='Preenchido quando esta é uma multa por Não Indicação de Condutor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_nic', to='multas.multa', verbose_name='multa original (para NIC)')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='frota.veiculo', verbose_name='veículo')),
                ('orgao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='multas.orgaoautuador', verbose_name='órgão autuador')),
            ],
            options={
                'verbose_name': 'multa',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMulta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da infração')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='código da infração')),
                ('ait', models.CharField(blank=True, max_length=30, verbose_name='AIT')),
                ('num_processamento', models.CharField(blank=True, max_length=30, verbose_name='nº de processamento')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição da infração')),
                ('local', models.CharField(blank=True, max_length=120, verbose_name='local')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor (R$)')),
                ('pontos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pontos na CNH')),
                ('resultado', models.CharField(choices=[('em_aberto', 'Em aberto'), ('advertencia', 'Convertida em advertência'), ('penalidade', 'Penalidade confirmada'), ('suspensa', 'Suspensa'), ('divida_ativa', 'Dívida ativa'), ('nao_exigivel', 'Não exigível'), ('cancelada', 'Cancelada')], default='em_aberto', max_length=15, verbose_name='resultado/situação')),
                ('tipo_condutor', models.CharField(choices=[('cliente', 'O próprio cliente'), ('outra_pessoa', 'Condutor autorizado / outra pessoa'), ('empresa', 'Empresa (dono absorve)')], default='cliente', max_length=15, verbose_name='tipo de condutor')),
                ('fici_status', models.CharField(choices=[('pendente', 'Pendente'), ('indicado', 'Indicado'), ('prazo_perdido', 'Prazo perdido')], default='pendente', max_length=15, verbose_name='indicação (FICI)')),
                ('fici_prazo', models.DateField(blank=True, null=True, verbose_name='prazo limite de indicação')),
                ('pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='pagamento')),
                ('pago_por', models.CharField(blank=True, max_length=80, verbose_name='pago por')),
                ('repasse', models.CharField(choices=[('nao_se_aplica', 'Não se aplica'), ('a_cobrar', 'A cobrar'), ('incluida_nd', 'Incluída em ND'), ('recebido', 'Recebido')], default='a_cobrar', max_length=15, verbose_name='repasse ao cliente')),
                ('responsavel', models.CharField(choices=[('cliente', 'Cliente da alocação'), ('condutor', 'Condutor identificado'), ('empresa', 'Empresa (absorve)'), ('vendedor', 'Vendedor anterior')], default='cliente', max_length=10, verbose_name='responsável pelo valor')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente_alocacao', models.ForeignKey(blank=True, db_constraint=False, help_text='Quem estava com o carro na data (preenchido automaticamente)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente da alocação')),
                ('condutor_autorizado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.condutorautorizado', verbose_name='condutor identificado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.veiculo', verbose_name='veículo')),
                ('multa_origem', models.ForeignKey(blank=True, db_constraint=False, help_text='Preenchido quando esta é uma multa por Não Indicação de Condutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multas.multa', verbose_name='multa original (para NIC)')),
                ('orgao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='multas.orgaoautuador', verbose_name='órgão autuador')),
            ],
            options={
                'verbose_name': 'historical multa',
                'verbose_name_plural': 'historical multas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
