# Generated by Django 5.2.16 on 2026-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorgaoautuador',
            name='login',
        ),
        migrations.RemoveField(
            model_name='historicalorgaoautuador',
            name='senha',
        ),
        migrations.AlterField(
            model_name='historicalorgaoautuador',
            name='procedimento',
            field=models.TextField(blank=True, help_text='Ex.: solicitar FICI e depois consultar; docs: CNH, contrato social...', verbose_name='procedimento / documentos exigidos'),
        ),
        migrations.AlterField(
            model_name='orgaoautuador',
            name='procedimento',
            field=models.TextField(blank=True, help_text='Ex.: solicitar FICI e depois consultar; docs: CNH, contrato social...', verbose_name='procedimento / documentos exigidos'),
        ),
    ]
