# Generated by Django 5.2.16 on 2026-07-20 00:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('intervalo_km_padrao', models.PositiveIntegerField(blank=True, help_text='Vazio = manutenção esporádica (sem ciclo por km)', null=True, verbose_name='intervalo padrão (km)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'item de manutenção',
                'verbose_name_plural': 'itens de manutenção',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalItemPreventiva',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=80, verbose_name='nome')),
                ('intervalo_km_padrao', models.PositiveIntegerField(blank=True, help_text='Vazio = manutenção esporádica (sem ciclo por km)', null=True, verbose_name='intervalo padrão (km)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item de manutenção',
                'verbose_name_plural': 'historical itens de manutenção',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalManutencao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('esporadica', 'Esporádica')], max_length=15, verbose_name='tipo')),
                ('data', models.DateField(verbose_name='data')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na execução')),
                ('descricao', models.TextField(help_text='Descreva o serviço feito — influencia a avaliação de desmobilização (docs.md §4.9)', verbose_name='descrição do reparo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.veiculo', verbose_name='veículo')),
                ('item', models.ForeignKey(blank=True, db_constraint=False, help_text='Preencher quando a manutenção corresponde a um item do plano (zera o ciclo)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manutencao.itempreventiva', verbose_name='item do plano')),
            ],
            options={
                'verbose_name': 'historical manutenção',
                'verbose_name_plural': 'historical manutenções',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIntervaloPersonalizado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('intervalo_km', models.PositiveIntegerField(verbose_name='intervalo (km)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.veiculo', verbose_name='veículo')),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manutencao.itempreventiva', verbose_name='item')),
            ],
            options={
                'verbose_name': 'historical intervalo personalizado',
                'verbose_name_plural': 'historical intervalos personalizados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('esporadica', 'Esporádica')], max_length=15, verbose_name='tipo')),
                ('data', models.DateField(verbose_name='data')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na execução')),
                ('descricao', models.TextField(help_text='Descreva o serviço feito — influencia a avaliação de desmobilização (docs.md §4.9)', verbose_name='descrição do reparo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('item', models.ForeignKey(blank=True, help_text='Preencher quando a manutenção corresponde a um item do plano (zera o ciclo)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='manutencao.itempreventiva', verbose_name='item do plano')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'manutenção',
                'verbose_name_plural': 'manutenções',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='IntervaloPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_km', models.PositiveIntegerField(verbose_name='intervalo (km)')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos_personalizados', to='frota.veiculo', verbose_name='veículo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervalos', to='manutencao.itempreventiva', verbose_name='item')),
            ],
            options={
                'verbose_name': 'intervalo personalizado',
                'verbose_name_plural': 'intervalos personalizados',
                'constraints': [models.UniqueConstraint(fields=('veiculo', 'item'), name='um_intervalo_por_item')],
            },
        ),
    ]
