# Generated by Django 5.2.16 on 2026-07-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_seed_itens_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanutencao',
            name='descricao',
            field=models.TextField(help_text='Descreva o serviço feito — pesa na avaliação de desmobilização (§4.9)', verbose_name='descrição do reparo'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.TextField(help_text='Descreva o serviço feito — pesa na avaliação de desmobilização (§4.9)', verbose_name='descrição do reparo'),
        ),
    ]
