# Generated by Django 5.2.16 on 2026-07-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_fornecedor_historicalfornecedor'),
        ('manutencao', '0002_seed_itens_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanutencao',
            name='custo_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gasto efetivo com oficina/associação (pode ser 0 se coberto por franquia)', max_digits=10, verbose_name='custo real da empresa (R$)'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='entrada na oficina'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='data_saida',
            field=models.DateField(blank=True, null=True, verbose_name='saída da oficina'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.fornecedor', verbose_name='oficina/fornecedor'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='origem_custo',
            field=models.CharField(choices=[('evento_protecao', 'Evento da proteção (Auto Truck)'), ('particular', 'Manutenção por fora (particular)')], default='particular', max_length=20, verbose_name='origem do custo'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='responsavel',
            field=models.CharField(choices=[('empresa', 'Empresa (dono)'), ('cliente', 'Cliente')], default='empresa', max_length=10, verbose_name='responsável pelo custo'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='status_repasse',
            field=models.CharField(choices=[('nao_se_aplica', 'Não se aplica'), ('a_cobrar', 'A cobrar'), ('cobrado', 'Cobrado'), ('recebido', 'Recebido')], default='nao_se_aplica', max_length=15, verbose_name='status de repasse ao cliente'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='valor_cobrado_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pode diferir do custo real', max_digits=10, null=True, verbose_name='valor cobrado do cliente (R$)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='custo_real',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gasto efetivo com oficina/associação (pode ser 0 se coberto por franquia)', max_digits=10, verbose_name='custo real da empresa (R$)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_entrada',
            field=models.DateField(blank=True, null=True, verbose_name='entrada na oficina'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_saida',
            field=models.DateField(blank=True, null=True, verbose_name='saída da oficina'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='frota.fornecedor', verbose_name='oficina/fornecedor'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='origem_custo',
            field=models.CharField(choices=[('evento_protecao', 'Evento da proteção (Auto Truck)'), ('particular', 'Manutenção por fora (particular)')], default='particular', max_length=20, verbose_name='origem do custo'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='responsavel',
            field=models.CharField(choices=[('empresa', 'Empresa (dono)'), ('cliente', 'Cliente')], default='empresa', max_length=10, verbose_name='responsável pelo custo'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='status_repasse',
            field=models.CharField(choices=[('nao_se_aplica', 'Não se aplica'), ('a_cobrar', 'A cobrar'), ('cobrado', 'Cobrado'), ('recebido', 'Recebido')], default='nao_se_aplica', max_length=15, verbose_name='status de repasse ao cliente'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='valor_cobrado_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pode diferir do custo real', max_digits=10, null=True, verbose_name='valor cobrado do cliente (R$)'),
        ),
        migrations.AlterField(
            model_name='historicalmanutencao',
            name='descricao',
            field=models.TextField(help_text='Descreva o serviço feito — pesa na avaliação de desmobilização (§4.9)', verbose_name='descrição do reparo'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.TextField(help_text='Descreva o serviço feito — pesa na avaliação de desmobilização (§4.9)', verbose_name='descrição do reparo'),
        ),
    ]
