# Generated by Django 5.2.16 on 2026-07-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_itemnotadebito_multa'),
        ('frota', '0002_fornecedor_historicalfornecedor'),
        ('manutencao', '0004_historicalmanutencao_cobranca_repasse_and_more'),
        ('sinistros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanutencao',
            name='sinistro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinistros.sinistro', verbose_name='sinistro'),
        ),
        migrations.AddField(
            model_name='historicalmanutencao',
            name='valor_cobrado_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pode ser diferente do custo real (maior ou menor)', max_digits=10, null=True, verbose_name='valor cobrado do cliente (R$)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='cobranca_repasse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencao_repassada', to='financeiro.cobranca', verbose_name='cobrança de repasse'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='custo_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pago à oficina/associação; zero se coberto por franquia gratuita', max_digits=10, null=True, verbose_name='custo real (R$)'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_entrada',
            field=models.DateField(blank=True, help_text='Preencher para acompanhar os dias parado (auxílio motorista >7 dias)', null=True, verbose_name='data de entrada na oficina'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='data_saida',
            field=models.DateField(blank=True, null=True, verbose_name='data de saída'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='frota.fornecedor', verbose_name='oficina/fornecedor'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='origem_custo',
            field=models.CharField(choices=[('protecao', 'Evento da proteção (Auto Truck)'), ('particular', 'Particular (por fora)')], default='particular', max_length=12, verbose_name='origem do custo'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='pagamento_custo',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10, verbose_name='pagamento à oficina'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='responsavel',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('cliente', 'Cliente')], default='empresa', max_length=10, verbose_name='responsável pelo custo'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='sinistro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='sinistros.sinistro', verbose_name='sinistro'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='valor_cobrado_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pode ser diferente do custo real (maior ou menor)', max_digits=10, null=True, verbose_name='valor cobrado do cliente (R$)'),
        ),
    ]
