# Generated by Django 5.2.16 on 2026-07-24 21:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alocacoes', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('alocacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='caucao', to='alocacoes.alocacao', verbose_name='alocação')),
            ],
            options={
                'verbose_name': 'caução',
                'verbose_name_plural': 'cauções',
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('aluguel', 'Aluguel semanal'), ('nota_debito', 'Nota de débito'), ('repasse_manutencao', 'Repasse de manutenção'), ('repasse_sinistro', 'Repasse de sinistro'), ('excedente_km', 'Excedente de km'), ('encargo', 'Encargo por atraso'), ('outro', 'Outro')], max_length=20, verbose_name='origem')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('judicial', 'Em cobrança judicial'), ('cancelada', 'Cancelada')], default='pendente', max_length=12, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('alocacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='alocacoes.alocacao', verbose_name='alocação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='pessoas.cliente', verbose_name='cliente')),
                ('cobranca_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encargos', to='financeiro.cobranca', verbose_name='cobrança que originou (encargo)')),
            ],
            options={
                'verbose_name': 'cobrança',
                'ordering': ['vencimento', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaucao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alocacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alocacoes.alocacao', verbose_name='alocação')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical caução',
                'verbose_name_plural': 'historical cauções',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovimentacaoCaucao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recebimento', 'Recebimento'), ('reforco', 'Reforço'), ('desconto', 'Desconto'), ('devolucao', 'Devolução')], max_length=15, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('data', models.DateField(verbose_name='data')),
                ('forma', models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=15, verbose_name='forma')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('caucao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.caucao')),
                ('cobranca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.cobranca', verbose_name='cobrança quitada (descontos)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical movimentação de caução',
                'verbose_name_plural': 'historical movimentações de caução',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNotaDebito',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, verbose_name='número')),
                ('data_emissao', models.DateField(verbose_name='data de emissão')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='vencimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nota de débito',
                'verbose_name_plural': 'historical notas de débito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecebimento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do recebimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor recebido (R$)')),
                ('forma', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('credito', 'Crédito do cliente')], default='pix', max_length=15, verbose_name='forma')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recebimento',
                'verbose_name_plural': 'historical recebimentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentacaoCaucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recebimento', 'Recebimento'), ('reforco', 'Reforço'), ('desconto', 'Desconto'), ('devolucao', 'Devolução')], max_length=15, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('data', models.DateField(verbose_name='data')),
                ('forma', models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=15, verbose_name='forma')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('caucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='financeiro.caucao')),
                ('cobranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descontos_caucao', to='financeiro.cobranca', verbose_name='cobrança quitada (descontos)')),
            ],
            options={
                'verbose_name': 'movimentação de caução',
                'verbose_name_plural': 'movimentações de caução',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='número')),
                ('data_emissao', models.DateField(verbose_name='data de emissão')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='vencimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='pessoas.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'nota de débito',
                'verbose_name_plural': 'notas de débito',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('nota_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.notadebito')),
            ],
            options={
                'verbose_name': 'item da nota de débito',
                'verbose_name_plural': 'itens da nota de débito',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCobranca',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('origem', models.CharField(choices=[('aluguel', 'Aluguel semanal'), ('nota_debito', 'Nota de débito'), ('repasse_manutencao', 'Repasse de manutenção'), ('repasse_sinistro', 'Repasse de sinistro'), ('excedente_km', 'Excedente de km'), ('encargo', 'Encargo por atraso'), ('outro', 'Outro')], max_length=20, verbose_name='origem')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('judicial', 'Em cobrança judicial'), ('cancelada', 'Cancelada')], default='pendente', max_length=12, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alocacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alocacoes.alocacao', verbose_name='alocação')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('cobranca_origem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.cobranca', verbose_name='cobrança que originou (encargo)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nota_debito', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.notadebito', verbose_name='nota de débito')),
            ],
            options={
                'verbose_name': 'historical cobrança',
                'verbose_name_plural': 'historical cobranças',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='nota_debito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobranca', to='financeiro.notadebito', verbose_name='nota de débito'),
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do recebimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor recebido (R$)')),
                ('forma', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('credito', 'Crédito do cliente')], default='pix', max_length=15, verbose_name='forma')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='pessoas.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'recebimento',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (sobra de pagamento)'), ('uso', 'Uso (abatimento em cobrança)')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('data', models.DateField(verbose_name='data')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='pessoas.cliente', verbose_name='cliente')),
                ('recebimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_credito', to='financeiro.recebimento')),
            ],
            options={
                'verbose_name': 'movimento de crédito',
                'verbose_name_plural': 'movimentos de crédito',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMovimentoCredito',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (sobra de pagamento)'), ('uso', 'Uso (abatimento em cobrança)')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('data', models.DateField(verbose_name='data')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recebimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.recebimento')),
            ],
            options={
                'verbose_name': 'historical movimento de crédito',
                'verbose_name_plural': 'historical movimentos de crédito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AplicacaoRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor aplicado (R$)')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='financeiro.cobranca')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='financeiro.recebimento')),
            ],
            options={
                'verbose_name': 'aplicação de recebimento',
                'verbose_name_plural': 'aplicações de recebimento',
            },
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.UniqueConstraint(condition=models.Q(('origem', 'aluguel')), fields=('alocacao', 'vencimento'), name='um_aluguel_por_alocacao_por_vencimento'),
        ),
    ]
