# Generated by Django 5.2.16 on 2026-07-21 15:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alocacoes', '0001_initial'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('retida', 'Retida'), ('parcial', 'Parcialmente utilizada'), ('devolvida', 'Devolvida')], default='retida', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('alocacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caucoes', to='alocacoes.alocacao', verbose_name='alocação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caucoes', to='pessoas.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'caução',
                'verbose_name_plural': 'cauções',
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('aluguel', 'Aluguel semanal'), ('nota_debito', 'Nota de débito'), ('manutencao', 'Repasse de manutenção'), ('sinistro', 'Repasse de sinistro'), ('excedente_km', 'Excedente de km'), ('encargo_atraso', 'Encargo por atraso')], max_length=20, verbose_name='origem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição/referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor devido (R$)')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('judicial', 'Em cobrança judicial')], default='pendente', max_length=12, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('alocacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='alocacoes.alocacao', verbose_name='alocação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='pessoas.cliente', verbose_name='cliente')),
                ('cobranca_origem', models.ForeignKey(blank=True, help_text='Para encargos: a cobrança atrasada que os gerou', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encargos', to='financeiro.cobranca', verbose_name='cobrança de origem')),
            ],
            options={
                'verbose_name': 'cobrança',
                'ordering': ['vencimento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaucao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('retida', 'Retida'), ('parcial', 'Parcialmente utilizada'), ('devolvida', 'Devolvida')], default='retida', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alocacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alocacoes.alocacao', verbose_name='alocação')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical caução',
                'verbose_name_plural': 'historical cauções',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCobranca',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('origem', models.CharField(choices=[('aluguel', 'Aluguel semanal'), ('nota_debito', 'Nota de débito'), ('manutencao', 'Repasse de manutenção'), ('sinistro', 'Repasse de sinistro'), ('excedente_km', 'Excedente de km'), ('encargo_atraso', 'Encargo por atraso')], max_length=20, verbose_name='origem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='descrição/referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor devido (R$)')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('judicial', 'Em cobrança judicial')], default='pendente', max_length=12, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('alocacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alocacoes.alocacao', verbose_name='alocação')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('cobranca_origem', models.ForeignKey(blank=True, db_constraint=False, help_text='Para encargos: a cobrança atrasada que os gerou', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.cobranca', verbose_name='cobrança de origem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cobrança',
                'verbose_name_plural': 'historical cobranças',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovimentacaoCaucao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reforco', 'Reforço'), ('desconto', 'Desconto'), ('devolucao', 'Devolução')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor (R$)')),
                ('data', models.DateField(verbose_name='data')),
                ('origem', models.CharField(blank=True, help_text='Ex.: nº da ND ou manutenção', max_length=200, verbose_name='origem')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('caucao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.caucao', verbose_name='caução')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical movimentação de caução',
                'verbose_name_plural': 'historical movimentações de caução',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNotaDebito',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='número')),
                ('data_emissao', models.DateField(verbose_name='data de emissão')),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('paga', 'Paga'), ('parcial', 'Parcial'), ('cancelada', 'Cancelada')], default='emitida', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('cobranca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.cobranca', verbose_name='cobrança gerada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nota de débito',
                'verbose_name_plural': 'historical notas de débito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecebimento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor recebido (R$)')),
                ('data', models.DateField(verbose_name='data do recebimento')),
                ('forma', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('caucao', 'Abatido da caução')], default='pix', max_length=15, verbose_name='forma')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recebimento',
                'verbose_name_plural': 'historical recebimentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentacaoCaucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reforco', 'Reforço'), ('desconto', 'Desconto'), ('devolucao', 'Devolução')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor (R$)')),
                ('data', models.DateField(verbose_name='data')),
                ('origem', models.CharField(blank=True, help_text='Ex.: nº da ND ou manutenção', max_length=200, verbose_name='origem')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('caucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='financeiro.caucao', verbose_name='caução')),
            ],
            options={
                'verbose_name': 'movimentação de caução',
                'verbose_name_plural': 'movimentações de caução',
                'ordering': ['data', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True, verbose_name='número')),
                ('data_emissao', models.DateField(verbose_name='data de emissão')),
                ('status', models.CharField(choices=[('emitida', 'Emitida'), ('paga', 'Paga'), ('parcial', 'Parcial'), ('cancelada', 'Cancelada')], default='emitida', max_length=10, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='pessoas.cliente', verbose_name='cliente')),
                ('cobranca', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nota_debito', to='financeiro.cobranca', verbose_name='cobrança gerada')),
            ],
            options={
                'verbose_name': 'nota de débito',
                'verbose_name_plural': 'notas de débito',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.notadebito', verbose_name='nota')),
            ],
            options={
                'verbose_name': 'item da nota de débito',
                'verbose_name_plural': 'itens da nota de débito',
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor recebido (R$)')),
                ('data', models.DateField(verbose_name='data do recebimento')),
                ('forma', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('caucao', 'Abatido da caução')], default='pix', max_length=15, verbose_name='forma')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='pessoas.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'recebimento',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BaixaCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas', to='financeiro.cobranca', verbose_name='cobrança')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas', to='financeiro.recebimento', verbose_name='recebimento')),
            ],
            options={
                'verbose_name': 'baixa de cobrança',
                'verbose_name_plural': 'baixas de cobrança',
            },
        ),
    ]
