# Generated by Django 5.2.16 on 2026-07-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotadebito',
            name='multa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_nd', to='multas.multa', verbose_name='multa'),
        ),
    ]
