# Generated by Django 5.2.16 on 2026-07-20 00:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistroKm',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Sempre dia 1º do mês', verbose_name='mês de referência')),
                ('data_leitura', models.DateField(verbose_name='data da leitura')),
                ('km', models.PositiveIntegerField(verbose_name='KM (odômetro)')),
                ('km_anterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM anterior')),
                ('dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='dias desde a leitura anterior')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'historical registro de KM',
                'verbose_name_plural': 'historical registros de KM',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RegistroKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Sempre dia 1º do mês', verbose_name='mês de referência')),
                ('data_leitura', models.DateField(verbose_name='data da leitura')),
                ('km', models.PositiveIntegerField(verbose_name='KM (odômetro)')),
                ('km_anterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM anterior')),
                ('dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='dias desde a leitura anterior')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_km', to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'registro de KM',
                'verbose_name_plural': 'registros de KM',
                'ordering': ['-mes_referencia'],
                'constraints': [models.UniqueConstraint(fields=('veiculo', 'mes_referencia'), name='um_registro_por_veiculo_por_mes')],
            },
        ),
    ]
