# Generated by Django 5.2.16 on 2026-08-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_itemnotadebito_multa'),
        ('km', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrokm',
            name='cobranca_excedente',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Gerada automaticamente quando a alocação limitada estoura a franquia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financeiro.cobranca', verbose_name='cobrança de excedente de km'),
        ),
        migrations.AddField(
            model_name='registrokm',
            name='cobranca_excedente',
            field=models.OneToOneField(blank=True, help_text='Gerada automaticamente quando a alocação limitada estoura a franquia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_km_excedente', to='financeiro.cobranca', verbose_name='cobrança de excedente de km'),
        ),
    ]
