# Generated by Django 5.2.16 on 2026-08-11 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_itemnotadebito_multa'),
        ('km', '0002_historicalregistrokm_cobranca_excedente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrokm',
            name='cobranca_excedente',
            field=models.OneToOneField(blank=True, help_text='Gerada automaticamente quando a alocação limitada estoura a franquia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registro_km_excedente', to='financeiro.cobranca', verbose_name='cobrança de excedente de km'),
        ),
    ]
