# Generated by Django 5.2.16 on 2026-07-19 23:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome completo')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, verbose_name='CNH — número')),
                ('cnh_categoria', models.CharField(blank=True, max_length=5, verbose_name='CNH — categoria')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='CNH — validade')),
                ('dia_vencimento', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Padrão: dia da semana em que pegou o carro', null=True, verbose_name='dia de vencimento semanal')),
                ('caucao_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Referência — a caução é opcional', max_digits=8, null=True, verbose_name='caução acordada (R$)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('inativo', 'Inativo')], default='ativo', max_length=15, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'cliente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CondutorAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, verbose_name='CNH — número')),
                ('contato', models.CharField(blank=True, max_length=80, verbose_name='contato')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condutores_autorizados', to='pessoas.cliente', verbose_name='cliente relacionado')),
            ],
            options={
                'verbose_name': 'condutor autorizado',
                'verbose_name_plural': 'condutores autorizados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome completo')),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, verbose_name='CNH — número')),
                ('cnh_categoria', models.CharField(blank=True, max_length=5, verbose_name='CNH — categoria')),
                ('cnh_validade', models.DateField(blank=True, null=True, verbose_name='CNH — validade')),
                ('dia_vencimento', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Padrão: dia da semana em que pegou o carro', null=True, verbose_name='dia de vencimento semanal')),
                ('caucao_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Referência — a caução é opcional', max_digits=8, null=True, verbose_name='caução acordada (R$)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inadimplente', 'Inadimplente'), ('inativo', 'Inativo')], default='ativo', max_length=15, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cliente',
                'verbose_name_plural': 'historical clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCondutorAutorizado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('cnh_numero', models.CharField(blank=True, max_length=20, verbose_name='CNH — número')),
                ('contato', models.CharField(blank=True, max_length=80, verbose_name='contato')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='cliente relacionado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical condutor autorizado',
                'verbose_name_plural': 'historical condutores autorizados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
