# Generated by Django 5.2.16 on 2026-08-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnh_frente',
            field=models.ImageField(blank=True, null=True, upload_to='cnh/', verbose_name='CNH — foto da frente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnh_verso',
            field=models.ImageField(blank=True, null=True, upload_to='cnh/', verbose_name='CNH — foto do verso'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, help_text='Aparece no card de clientes e na ficha', null=True, upload_to='clientes/', verbose_name='foto do motorista'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='cnh_frente',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='CNH — foto da frente'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='cnh_verso',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='CNH — foto do verso'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='foto',
            field=models.TextField(blank=True, help_text='Aparece no card de clientes e na ficha', max_length=100, null=True, verbose_name='foto do motorista'),
        ),
    ]
