# Generated by Django 5.2.16 on 2026-08-18 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_cliente_cnh_frente_cliente_cnh_verso_cliente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnh_frente',
            field=models.FileField(blank=True, null=True, upload_to='cnh/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='CNH — frente (foto ou PDF)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnh_verso',
            field=models.FileField(blank=True, null=True, upload_to='cnh/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='CNH — verso (foto ou PDF)'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='cnh_frente',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='CNH — frente (foto ou PDF)'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='cnh_verso',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='CNH — verso (foto ou PDF)'),
        ),
    ]
