# Generated by Django 5.2.16 on 2026-07-19 23:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('valor_semanal_referencia', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor semanal de referência (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoria',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=50, verbose_name='nome')),
                ('valor_semanal_referencia', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor semanal de referência (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical categoria',
                'verbose_name_plural': 'historical categorias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVeiculo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('placa', models.CharField(db_index=True, max_length=8, verbose_name='placa')),
                ('renavam', models.CharField(blank=True, max_length=20, verbose_name='renavam')),
                ('chassi', models.CharField(blank=True, max_length=30, verbose_name='chassi')),
                ('marca_modelo', models.CharField(max_length=80, verbose_name='marca/modelo')),
                ('ano', models.CharField(blank=True, help_text='Ex.: "20/21"', max_length=10, verbose_name='ano')),
                ('uso', models.CharField(choices=[('locacao', 'Locação'), ('fora_locacao', 'Fora de locação')], default='locacao', max_length=20, verbose_name='uso')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alocado', 'Alocado'), ('em_manutencao', 'Em manutenção'), ('inativo', 'Inativo'), ('vendido', 'Vendido')], default='disponivel', max_length=20, verbose_name='status')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='data de aquisição')),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor de compra (R$)')),
                ('km_compra', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na compra')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='KM atual')),
                ('valor_venda_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='FIPE/mercado, atualizado manualmente — usado na desmobilização', max_digits=10, null=True, verbose_name='valor estimado de venda (R$)')),
                ('chave_reserva', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('duvida', 'Dúvida')], default='duvida', max_length=10, verbose_name='chave reserva')),
                ('rastreador_fornecedor', models.CharField(blank=True, max_length=80, verbose_name='rastreador — fornecedor')),
                ('rastreador_vigencia_fim', models.DateField(blank=True, null=True, verbose_name='rastreador — fim da vigência')),
                ('bateria_data_troca', models.DateField(blank=True, null=True, verbose_name='bateria — data da troca')),
                ('bateria_fornecedor', models.CharField(blank=True, max_length=80, verbose_name='bateria — fornecedor')),
                ('bateria_garantia_fim', models.DateField(blank=True, null=True, verbose_name='bateria — fim da garantia')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.categoria', verbose_name='categoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical veículo',
                'verbose_name_plural': 'historical veículos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True, verbose_name='placa')),
                ('renavam', models.CharField(blank=True, max_length=20, verbose_name='renavam')),
                ('chassi', models.CharField(blank=True, max_length=30, verbose_name='chassi')),
                ('marca_modelo', models.CharField(max_length=80, verbose_name='marca/modelo')),
                ('ano', models.CharField(blank=True, help_text='Ex.: "20/21"', max_length=10, verbose_name='ano')),
                ('uso', models.CharField(choices=[('locacao', 'Locação'), ('fora_locacao', 'Fora de locação')], default='locacao', max_length=20, verbose_name='uso')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alocado', 'Alocado'), ('em_manutencao', 'Em manutenção'), ('inativo', 'Inativo'), ('vendido', 'Vendido')], default='disponivel', max_length=20, verbose_name='status')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='data de aquisição')),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor de compra (R$)')),
                ('km_compra', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na compra')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='KM atual')),
                ('valor_venda_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='FIPE/mercado, atualizado manualmente — usado na desmobilização', max_digits=10, null=True, verbose_name='valor estimado de venda (R$)')),
                ('chave_reserva', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('duvida', 'Dúvida')], default='duvida', max_length=10, verbose_name='chave reserva')),
                ('rastreador_fornecedor', models.CharField(blank=True, max_length=80, verbose_name='rastreador — fornecedor')),
                ('rastreador_vigencia_fim', models.DateField(blank=True, null=True, verbose_name='rastreador — fim da vigência')),
                ('bateria_data_troca', models.DateField(blank=True, null=True, verbose_name='bateria — data da troca')),
                ('bateria_fornecedor', models.CharField(blank=True, max_length=80, verbose_name='bateria — fornecedor')),
                ('bateria_garantia_fim', models.DateField(blank=True, null=True, verbose_name='bateria — fim da garantia')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'veículo',
                'ordering': ['placa'],
            },
        ),
    ]
