# Generated by Django 5.2.16 on 2026-07-21 16:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome/razão social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=80, verbose_name='contato')),
                ('tipo_servico', models.CharField(blank=True, help_text='mecânica, funilaria, bateria, rastreador...', max_length=120, verbose_name='tipo de serviço')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFornecedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome/razão social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=80, verbose_name='contato')),
                ('tipo_servico', models.CharField(blank=True, help_text='mecânica, funilaria, bateria, rastreador...', max_length=120, verbose_name='tipo de serviço')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fornecedor',
                'verbose_name_plural': 'historical fornecedors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
