# Generated by Django 5.2.16 on 2026-07-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_fornecedor_historicalfornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalveiculo',
            name='comprador',
            field=models.CharField(blank=True, max_length=100, verbose_name='comprador'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='custos_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Documentação, transferência, emplacamento', max_digits=10, null=True, verbose_name='custos de entrada (R$)'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='custos_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custos da venda (R$)'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='data_venda',
            field=models.DateField(blank=True, null=True, verbose_name='data da venda'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='km_venda',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na venda'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='mensalidade_protecao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mensalidade da Auto Truck (frota) — entra nas despesas do veículo', max_digits=8, null=True, verbose_name='mensalidade da proteção "$ AT" (R$)'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor da venda (R$)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='comprador',
            field=models.CharField(blank=True, max_length=100, verbose_name='comprador'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='custos_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Documentação, transferência, emplacamento', max_digits=10, null=True, verbose_name='custos de entrada (R$)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='custos_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custos da venda (R$)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_venda',
            field=models.DateField(blank=True, null=True, verbose_name='data da venda'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='km_venda',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM na venda'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='mensalidade_protecao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mensalidade da Auto Truck (frota) — entra nas despesas do veículo', max_digits=8, null=True, verbose_name='mensalidade da proteção "$ AT" (R$)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor da venda (R$)'),
        ),
    ]
