# Generated by Django 5.2.16 on 2026-08-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_seed_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalveiculo',
            name='foto',
            field=models.TextField(blank=True, help_text='Aparece no card da frota e na ficha do veículo', max_length=100, null=True, verbose_name='foto do carro'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='ipva_ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IPVA — ano'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='ipva_pago_em',
            field=models.DateField(blank=True, help_text='Preencha ao pagar — a data define o mês da despesa nos relatórios', null=True, verbose_name='IPVA — pago em'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='ipva_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IPVA — valor (R$)'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='ipva_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='IPVA — vencimento'),
        ),
        migrations.AddField(
            model_name='historicalveiculo',
            name='licenciamento_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='licenciamento — vencimento'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Aparece no card da frota e na ficha do veículo', null=True, upload_to='veiculos/', verbose_name='foto do carro'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ipva_ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='IPVA — ano'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ipva_pago_em',
            field=models.DateField(blank=True, help_text='Preencha ao pagar — a data define o mês da despesa nos relatórios', null=True, verbose_name='IPVA — pago em'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ipva_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IPVA — valor (R$)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ipva_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='IPVA — vencimento'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='licenciamento_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='licenciamento — vencimento'),
        ),
    ]
