# Generated by Django 5.2.16 on 2026-08-18 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_historicalveiculo_foto_historicalveiculo_ipva_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalveiculo',
            name='documento',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='documento do carro — CRLV (foto ou PDF)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='veiculos/documentos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='documento do carro — CRLV (foto ou PDF)'),
        ),
    ]
