# Generated by Django 5.2.16 on 2026-07-21 16:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0002_fornecedor_historicalfornecedor'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSinistro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('tipo', models.CharField(choices=[('colisao', 'Colisão/avaria'), ('roubo_furto', 'Roubo/furto'), ('outro', 'Outro')], default='colisao', max_length=15, verbose_name='tipo')),
                ('envolvido', models.CharField(choices=[('associado', 'Associado (nosso condutor)'), ('terceiro', 'Terceiro')], max_length=10, verbose_name='envolvido')),
                ('responsabilidade', models.CharField(choices=[('cliente', 'Cliente/associado'), ('terceiro', 'Terceiro'), ('indefinida', 'Indefinida')], default='indefinida', max_length=12, verbose_name='responsabilidade')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição do ocorrido')),
                ('boletim_ocorrencia', models.CharField(blank=True, max_length=40, verbose_name='boletim de ocorrência (nº)')),
                ('acionou_protecao', models.BooleanField(default=False, verbose_name='acionou a proteção (evento Auto Truck)?')),
                ('data_evento', models.DateField(blank=True, null=True, verbose_name='data do evento')),
                ('franquia_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Pode ser 0 se coberta pela taxa de franquias gratuitas', max_digits=10, null=True, verbose_name='cota/franquia usada (R$)')),
                ('situacao_veiculo', models.CharField(blank=True, max_length=120, verbose_name='situação do veículo (roubo/furto)')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('regularizacao', 'Em regularização'), ('concluido', 'Concluído')], default='aberto', max_length=15, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(blank=True, db_constraint=False, help_text='Cliente vigente na data (preenchido automaticamente)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.cliente', verbose_name='motorista')),
                ('veiculo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'historical sinistro',
                'verbose_name_plural': 'historical sinistros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('tipo', models.CharField(choices=[('colisao', 'Colisão/avaria'), ('roubo_furto', 'Roubo/furto'), ('outro', 'Outro')], default='colisao', max_length=15, verbose_name='tipo')),
                ('envolvido', models.CharField(choices=[('associado', 'Associado (nosso condutor)'), ('terceiro', 'Terceiro')], max_length=10, verbose_name='envolvido')),
                ('responsabilidade', models.CharField(choices=[('cliente', 'Cliente/associado'), ('terceiro', 'Terceiro'), ('indefinida', 'Indefinida')], default='indefinida', max_length=12, verbose_name='responsabilidade')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição do ocorrido')),
                ('boletim_ocorrencia', models.CharField(blank=True, max_length=40, verbose_name='boletim de ocorrência (nº)')),
                ('acionou_protecao', models.BooleanField(default=False, verbose_name='acionou a proteção (evento Auto Truck)?')),
                ('data_evento', models.DateField(blank=True, null=True, verbose_name='data do evento')),
                ('franquia_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Pode ser 0 se coberta pela taxa de franquias gratuitas', max_digits=10, null=True, verbose_name='cota/franquia usada (R$)')),
                ('situacao_veiculo', models.CharField(blank=True, max_length=120, verbose_name='situação do veículo (roubo/furto)')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('regularizacao', 'Em regularização'), ('concluido', 'Concluído')], default='aberto', max_length=15, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motorista', models.ForeignKey(blank=True, help_text='Cliente vigente na data (preenchido automaticamente)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sinistros', to='pessoas.cliente', verbose_name='motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinistros', to='frota.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'sinistro',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAuxilioMotorista',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dias_parado', models.PositiveIntegerField(blank=True, null=True, verbose_name='dias parado')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Um salário mínimo (docs.md decisão nº 10)', max_digits=10, null=True, verbose_name='valor (R$)')),
                ('status', models.CharField(choices=[('a_solicitar', 'A solicitar'), ('solicitado', 'Solicitado'), ('recebido', 'Recebido')], default='a_solicitar', max_length=12, verbose_name='status')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='data do recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sinistro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinistros.sinistro', verbose_name='sinistro')),
            ],
            options={
                'verbose_name': 'historical auxílio motorista profissional',
                'verbose_name_plural': 'historical auxílios motorista profissional',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AuxilioMotorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_parado', models.PositiveIntegerField(blank=True, null=True, verbose_name='dias parado')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Um salário mínimo (docs.md decisão nº 10)', max_digits=10, null=True, verbose_name='valor (R$)')),
                ('status', models.CharField(choices=[('a_solicitar', 'A solicitar'), ('solicitado', 'Solicitado'), ('recebido', 'Recebido')], default='a_solicitar', max_length=12, verbose_name='status')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='data do recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('sinistro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auxilios', to='sinistros.sinistro', verbose_name='sinistro')),
            ],
            options={
                'verbose_name': 'auxílio motorista profissional',
                'verbose_name_plural': 'auxílios motorista profissional',
                'ordering': ['-id'],
            },
        ),
    ]
